bindd = SUPER, a, Toggle scratchpad A, togglespecialworkspace, scratchpadA
bindd = SUPER ALT, a, Move window to scratchpad A, movetoworkspacesilent, special:scratchpadA


bindd = SUPER, d, Toggle scratchpad D, togglespecialworkspace, scratchpadD
bindd = SUPER ALT, d, Move window to scratchpad D, movetoworkspacesilent, special:scratchpadD


